// <auto-generated />
namespace FitnessWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class IniDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IniDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202506071303211_IniDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
